name: baseshift
summary: CLI Tool
description: |
  A CLI tool that converts number system. This will support
  binary, decimal, octal, and hexadecimal system.
version: "1.5.0"
grade: stable
base: core20
confinement: strict
apps:
  baseshift:
    command: bin/baseshift
parts:
  baseshift:
    plugin: go
    source-type: git
    source: https://github.com/kentlouisetonino/baseshift.git
